Repository wieslawsoltes/Xaml.Behaviors, pull requests merged in 2025-06, with the labels that each got.

#197 Add double-tap inline edit samples
  samples/BehaviorsTestApplication/Controls/EditableItem.axaml
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/EditableDoubleTappedListBoxView.axaml
  samples/BehaviorsTestApplication/Views/Pages/EditableDoubleTappedListBoxView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/EditableDoubleTappedTreeViewView.axaml
  samples/BehaviorsTestApplication/Views/Pages/EditableDoubleTappedTreeViewView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/Control/InlineEditBehavior.cs
Labels: size/L, codex

#190 Add window interactions
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/WindowInteractionsView.axaml
  samples/BehaviorsTestApplication/Views/Pages/WindowInteractionsView.axaml.cs
  samples/BehaviorsTestApplication/Views/Windows/SampleWindow.axaml
  samples/BehaviorsTestApplication/Views/Windows/SampleWindow.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/Window/CenterWindowBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/Window/CloseWindowAction.cs
  src/Xaml.Behaviors.Interactions.Custom/Window/ShowWindowAction.cs
  src/Xaml.Behaviors.Interactions.Custom/Window/WindowStateTrigger.cs
Labels: size/L, codex

#221 Missing “return”
  src/Xaml.Behaviors.Interactions.DragAndDrop/ContextDragBehaviorBase.cs
Labels: size/S

#189 Add dialog interaction classes and sample
  README.md
  samples/BehaviorsTestApplication/Dialogs/SimpleDialog.axaml
  samples/BehaviorsTestApplication/Dialogs/SimpleDialog.axaml.cs
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DialogActionView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DialogActionView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/Dialog/DialogClosedTrigger.cs
  src/Xaml.Behaviors.Interactions.Custom/Dialog/DialogOpenedTrigger.cs
  src/Xaml.Behaviors.Interactions.Custom/Dialog/ShowDialogAction.cs
Labels: size/L, codex

#193 Add TabControl behaviors and actions
  README.md
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/TabControlNavigationView.axaml
  samples/BehaviorsTestApplication/Views/Pages/TabControlNavigationView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/TabControlSelectionChangedTriggerView.axaml
  samples/BehaviorsTestApplication/Views/Pages/TabControlSelectionChangedTriggerView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/TabControl/TabControlKeyNavigationBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/TabControl/TabControlNextAction.cs
  src/Xaml.Behaviors.Interactions.Custom/TabControl/TabControlPreviousAction.cs
  src/Xaml.Behaviors.Interactions.Custom/TabControl/TabControlSelectionChangedTrigger.cs
Labels: size/L, codex

#194 Add icon interactions and sample
  samples/BehaviorsTestApplication/ViewModels/IconViewModel.cs
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/IconView.axaml
  samples/BehaviorsTestApplication/Views/Pages/IconView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/Icon/PathIconDataBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/Icon/PathIconDataChangedTrigger.cs
  src/Xaml.Behaviors.Interactions.Custom/Icon/SetPathIconDataAction.cs
Labels: size/L, codex

#191 Add popup behaviors, triggers, and actions
  README.md
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/PopupEventTriggersView.axaml
  samples/BehaviorsTestApplication/Views/Pages/PopupEventTriggersView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/ShowHidePopupActionView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ShowHidePopupActionView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/Actions/HidePopupAction.cs
  src/Xaml.Behaviors.Interactions.Custom/Actions/ShowPopupAction.cs
  src/Xaml.Behaviors.Interactions.Custom/Button/ButtonHidePopupOnClickBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/Popup/PopupClosedTrigger.cs
  src/Xaml.Behaviors.Interactions.Custom/Popup/PopupOpenedTrigger.cs
Labels: size/L, codex

#224 Refactor common code into PropertyHelper
  src/Xaml.Behaviors.Interactions/Core/ChangePropertyAction.cs
  src/Xaml.Behaviors.Interactivity/Helpers/PropertyHelper.cs
Labels: size/XL

#212 Add view model property interactions
  README.md
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ViewModelPropertyActionsView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ViewModelPropertyActionsView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/ViewModel/IncrementViewModelPropertyAction.cs
  src/Xaml.Behaviors.Interactions.Custom/ViewModel/SetViewModelPropertyAction.cs
  src/Xaml.Behaviors.Interactions.Custom/ViewModel/SetViewModelPropertyOnLoadBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/ViewModel/ToggleViewModelBooleanAction.cs
  src/Xaml.Behaviors.Interactions.Custom/ViewModel/ViewModelPropertyChangedTrigger.cs
Labels: size/L, codex

#226 Move to Interactivity project
  src/Xaml.Behaviors.Interactions.Custom/Button/ButtonHideFlyoutBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/Control/HideAttachedFlyoutBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/Validation/SliderValidationBehavior.cs
  src/Xaml.Behaviors.Interactions.DragAndDrop/DropBehaviorBase.cs
  src/Xaml.Behaviors.Interactions.DragAndDrop/Xaml.Behaviors.Interactions.DragAndDrop.csproj
  src/Xaml.Behaviors.Interactions/StorageProvider/Core/PickerBehaviorBase.cs
  src/Xaml.Behaviors.Interactivity/Behaviors/DisposingBehavior.cs
  src/Xaml.Behaviors.Interactivity/ExecuteCommand/InvokeCommandBehaviorBase.cs
  src/Xaml.Behaviors.Interactivity/Triggers/DisposingTrigger.cs
Labels: size/S

#209 Add drag preview behaviors and sample
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/FilesPreviewView.axaml
  samples/BehaviorsTestApplication/Views/Pages/FilesPreviewView.axaml.cs
  src/Xaml.Behaviors.Interactions.DragAndDrop/AddPreviewFilesAction.cs
  src/Xaml.Behaviors.Interactions.DragAndDrop/DragOverEventTrigger.cs
  src/Xaml.Behaviors.Interactions.DragAndDrop/FilesPreviewBehavior.cs
Labels: size/L, codex

#192 Add AutoCompleteBox interactions
  README.md
  samples/BehaviorsTestApplication/ViewModels/MainWindowViewModel.cs
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/AutoCompleteBoxView.axaml
  samples/BehaviorsTestApplication/Views/Pages/AutoCompleteBoxView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/AutoCompleteBox/AutoCompleteBoxOpenDropDownOnFocusBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/AutoCompleteBox/AutoCompleteBoxSelectionChangedTrigger.cs
  src/Xaml.Behaviors.Interactions.Custom/AutoCompleteBox/ClearAutoCompleteBoxSelectionAction.cs
Labels: size/L, codex

#201 Add async upload interactions
  samples/BehaviorsTestApplication/ViewModels/MainWindowViewModel.cs
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/UploadFileView.axaml
  samples/BehaviorsTestApplication/Views/Pages/UploadFileView.axaml.cs
  src/Xaml.Behaviors.Interactions/FileUpload/ButtonUploadFileBehavior.cs
  src/Xaml.Behaviors.Interactions/FileUpload/UploadCompletedTrigger.cs
  src/Xaml.Behaviors.Interactions/FileUpload/UploadFileAction.cs
  src/Xaml.Behaviors.Interactions/FileUpload/UploadFileBehaviorBase.cs
Labels: size/L, codex

#203 Add delayed load behaviors and samples
  README.md
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DelayedLoadBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DelayedLoadBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/DelayedLoadTriggerView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DelayedLoadTriggerView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/DelayedShowControlActionView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DelayedShowControlActionView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/Actions/DelayedShowControlAction.cs
  src/Xaml.Behaviors.Interactions.Custom/Control/DelayedLoadBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/Core/DelayedLoadTrigger.cs
Labels: size/L, codex

#228 Move base behaviors and actions to Interactivity project
  src/Xaml.Behaviors.Interactions.Custom/Actions/CallMethodAsyncAction.cs
  src/Xaml.Behaviors.Interactions.Custom/Core/AsyncLoadBehavior.cs
  src/Xaml.Behaviors.Interactions.DragAndDrop/DragOverEventTrigger.cs
  src/Xaml.Behaviors.Interactions.Events/DragEnterEventTrigger.cs
  src/Xaml.Behaviors.Interactions.Events/DragLeaveEventTrigger.cs
  src/Xaml.Behaviors.Interactions.Events/DragOverEventTrigger.cs
  src/Xaml.Behaviors.Interactions.Events/DropEventTrigger.cs
  src/Xaml.Behaviors.Interactions/Clipboard/GetClipboardDataAction.cs
  src/Xaml.Behaviors.Interactions/Clipboard/GetClipboardFormatsAction.cs
  src/Xaml.Behaviors.Interactions/Clipboard/GetClipboardTextAction.cs
  src/Xaml.Behaviors.Interactions/Core/EventTrigger.cs
  src/Xaml.Behaviors.Interactions/Core/EventTriggerBehavior.cs
  src/Xaml.Behaviors.Interactions/Core/InvokeCommandAction.cs
  src/Xaml.Behaviors.Interactions/Core/TimerTrigger.cs
  src/Xaml.Behaviors.Interactions/FileUpload/UploadFileAction.cs
  src/Xaml.Behaviors.Interactions/StorageProvider/Core/PickerActionBase.cs
  src/Xaml.Behaviors.Interactivity/Actions/InvokeCommandActionBase.cs
  src/Xaml.Behaviors.Interactivity/Behaviors/InteractiveBehaviorBase.cs
  src/Xaml.Behaviors.Interactivity/Behaviors/InvokeCommandBehaviorBase.cs
  src/Xaml.Behaviors.Interactivity/Triggers/EventTriggerBase.cs
  src/Xaml.Behaviors.Interactivity/Triggers/InteractiveTriggerBase.cs
Labels: size/XL

#208 Add context dialog support
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ContextDialogView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ContextDialogView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/ContextDialogs/ContextDialogBehavior.cs
  src/Xaml.Behaviors.Interactions.Custom/ContextDialogs/ContextDialogClosedTrigger.cs
  src/Xaml.Behaviors.Interactions.Custom/ContextDialogs/ContextDialogOpenedTrigger.cs
  src/Xaml.Behaviors.Interactions.Custom/ContextDialogs/HideContextDialogAction.cs
  src/Xaml.Behaviors.Interactions.Custom/ContextDialogs/ShowContextDialogAction.cs
Labels: size/L, codex

#230 Add agent instructions for Codex
  AGENTS.md
Labels: size/M, codex

#232 Add sorting option to SelectingItemsControlSearchBehavior
  README.md
  samples/BehaviorsTestApplication/Views/MainView.axaml
  src/Xaml.Behaviors.Interactions.Custom/SelectingItemsControl/SelectingItemsControlSearchBehavior.cs
Labels: size/M, codex

#235 Add missing trigger sample pages
  README.md
  samples/BehaviorsTestApplication/Behaviors/ActualThemeVariantChangedMessageBehavior.cs
  samples/BehaviorsTestApplication/Behaviors/AttachedToLogicalTreeMessageBehavior.cs
  samples/BehaviorsTestApplication/Behaviors/DataContextChangedMessageBehavior.cs
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ActualThemeVariantChangedBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ActualThemeVariantChangedBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/AttachedToLogicalTreeBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/AttachedToLogicalTreeBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/AttachedToLogicalTreeTriggerView.axaml
  samples/BehaviorsTestApplication/Views/Pages/AttachedToLogicalTreeTriggerView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/AttachedToVisualTreeTriggerView.axaml
  samples/BehaviorsTestApplication/Views/Pages/AttachedToVisualTreeTriggerView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/BindingBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/BindingBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/ContextDialogView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DataContextChangedBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DataContextChangedBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/DataContextChangedTriggerView.axaml
  samples/BehaviorsTestApplication/Views/Pages/DataContextChangedTriggerView.axaml.cs
Labels: size/L, codex

#234 Add sample pages for new behaviors
  README.md
  samples/BehaviorsTestApplication/Views/MainView.axaml
  samples/BehaviorsTestApplication/Views/Pages/AnimationBuilderView.axaml
  samples/BehaviorsTestApplication/Views/Pages/AnimationBuilderView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/ButtonExecuteCommandOnKeyDownBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ButtonExecuteCommandOnKeyDownBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/ButtonHideFlyoutBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ButtonHideFlyoutBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/ButtonHideFlyoutOnClickBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/ButtonHideFlyoutOnClickBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/CarouselSelectionChangedTriggerView.axaml
  samples/BehaviorsTestApplication/Views/Pages/CarouselSelectionChangedTriggerView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/FocusAutoCompleteBoxTextBoxBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/FocusAutoCompleteBoxTextBoxBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/RemoveRangeActionView.axaml
  samples/BehaviorsTestApplication/Views/Pages/RemoveRangeActionView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/SelectingItemsControlBehaviorView.axaml
  samples/BehaviorsTestApplication/Views/Pages/SelectingItemsControlBehaviorView.axaml.cs
  samples/BehaviorsTestApplication/Views/Pages/StartAnimationActionView.axaml
  samples/BehaviorsTestApplication/Views/Pages/StartAnimationActionView.axaml.cs
  src/Xaml.Behaviors.Interactions.Custom/Collections/RemoveRangeAction.cs
Labels: size/L, codex

#238 Add more DataTriggerBehavior headless tests
  tests/Xaml.Behaviors.Interactions.UnitTests/Core/DataTriggerBehavior002.axaml
  tests/Xaml.Behaviors.Interactions.UnitTests/Core/DataTriggerBehavior002.axaml.cs
  tests/Xaml.Behaviors.Interactions.UnitTests/Core/DataTriggerBehavior003.axaml
  tests/Xaml.Behaviors.Interactions.UnitTests/Core/DataTriggerBehavior003.axaml.cs
  tests/Xaml.Behaviors.Interactions.UnitTests/Core/DataTriggerBehaviorTests.cs
Labels: size/L, codex
