Repository wieslawsoltes/Xaml.Behaviors, pull requests merged in 2025-04, with the labels that each got.

#37 sample: TreeView drag-and-drop with highlight effects
  samples/BehaviorsTestApplication/Behaviors/BaseTreeViewDropHandler.cs
  samples/BehaviorsTestApplication/Behaviors/NodesTreeViewDropHandler.cs
  samples/BehaviorsTestApplication/ViewModels/DragAndDropSampleViewModel.cs
  samples/BehaviorsTestApplication/ViewModels/DragNodeViewModel.cs
  samples/BehaviorsTestApplication/Views/Pages/DragAndDropView.axaml
Labels: size/L

#54 Update build system
  AvaloniaBehaviors.sln
  Directory.Build.props
  Directory.Packages.props
  azure-pipelines.yml
  build/build/Build.cs
  samples/Directory.Packages.props
  src/Avalonia.Xaml.Interactivity/Interaction.cs
  tests/Directory.Packages.props
Labels: size/L

#57 Fix detaching from visual tree
  src/Avalonia.Xaml.Interactivity/StyledElement/StyledElementAction.cs
  src/Avalonia.Xaml.Interactivity/StyledElement/StyledElementBehavior.cs
Labels: size/S

#59 Fix ConvertFromInvariantString exception handling in TypeConverterHelper
  src/Avalonia.Xaml.Interactivity/Helpers/TypeConverterHelper.cs
Labels: size/XS

#60 Check result from TypeConverterHelper,Convert
  src/Avalonia.Xaml.Interactions/Core/ChangePropertyAction.cs
  src/Avalonia.Xaml.Interactivity/Helpers/ComparisonConditionTypeHelper.cs
Labels: size/M

#61 Add support for Parse convention method in the TypeConverterHelper
  src/Avalonia.Xaml.Interactivity/Helpers/TypeConverterHelper.cs
Labels: size/M

#62 Fix ComparisonConditionTypeHelper to convert only if value is a string
  src/Avalonia.Xaml.Interactivity/Helpers/ComparisonConditionTypeHelper.cs
Labels: size/XS
